status ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -80,3 +80,17 @@ jobs:
       uses: securego/gosec@master
       with:
         args: './...'
+
+  ci-status:
+    runs-on: ubuntu-latest
+    needs: [test, lint, security]
+    if: always()
+    steps:
+    - name: status-check
+      run: |
+        if [[ "${{ needs.test.result }}" != "success" || "${{ needs.lint.result }}" != "success" || "${{ needs.security.result }}" != "success" ]]; then
+          echo "One or more jobs failed"
+          exit 1
+        else
+          echo "All jobs passed successfully"
+        fi
